runtime: nodejs
vm: true

skip_files:
  - ^(.*/)?.*/node_modules/.*$

manual_scaling:
  instances: 1

env_variables:
  ADAPTER: slack
  BOT_NAME: testhbot
  HUBOT_SLACK_TOKEN: xoxb-24639993351-YDhl2BDZgjOUKXtq83wXhsFl
  EXPRESS_PORT: 80
  HUBOT_LOG_LEVEL: debug
